name: Secure CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to 'main'

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Scan for hardcoded secrets using Gitleaks
    - name: Scan Secrets with Gitleaks
      uses: gitleaks/gitleaks-action@v2

    # Step 3: Login to DockerHub
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build Docker image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-secure-app:latest .

    # Step 5: Scan image for vulnerabilities using Trivy
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/demo-secure-app:latest
        format: table
        exit-code: 1           # Fail if vulnerabilities found
        ignore-unfixed: true   # Don't fail for known unfixed issues

    # Step 6: Push image to DockerHub
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/demo-secure-app:latest
